using BaseLib.Abstracts;
using BaseLib.Utils.NodeFactories;
using ElKid.ElKidCode.Extensions;
using Godot;
using MegaCrit.Sts2.Core.Entities.Characters;
using MegaCrit.Sts2.Core.Models;
using ElKid.ElKidCode.Cards;
using ElKid.ElKidCode.Relics;

namespace ElKid.ElKidCode.Character;

public class ElKid : PlaceholderCharacterModel
{
    public const string CharacterId = "ElKid";
    
    public static readonly Color Color = new("5fd3ff");

    public override Color NameColor => Color;
    public override CharacterGender Gender => CharacterGender.Masculine;
    public override int StartingHp => 70;

    /// <summary>
    /// Testing aid: when true, the run starts with one copy of every card in the pool instead of the normal deck.
    /// Set back to false before playing normally.
    /// </summary>
    private const bool TestDeck = false;

    public override IEnumerable<CardModel> StartingDeck => TestDeck ? TestingDeck : NormalDeck;

    private static IEnumerable<CardModel> TestingDeck => [
        ModelDb.Card<BlinkStep>(), ModelDb.Card<WindUp>(),
        ModelDb.Card<Quickdraw>(), ModelDb.Card<FlashCut>(), ModelDb.Card<Sidestep>(),
        ModelDb.Card<ShadowStep>(), ModelDb.Card<Parry>(), ModelDb.Card<Riposte>(),
        ModelDb.Card<WhirlingBlade>(), ModelDb.Card<Haste>(), ModelDb.Card<BloodClock>(),
        ModelDb.Card<BleedingEdge>(), ModelDb.Card<EchoStep>(), ModelDb.Card<Countdown>(),
        ModelDb.Card<HourglassGuard>(), ModelDb.Card<BorrowedTime>(), ModelDb.Card<Quicksilver>(),
        ModelDb.Card<Flurry>(), ModelDb.Card<ThousandCuts>(), ModelDb.Card<TimeStop>(),
        ModelDb.Card<ClockworkHeart>(), ModelDb.Card<BloodForTime>()
    ];

    private static IEnumerable<CardModel> NormalDeck => [
        ModelDb.Card<ElKidStrike>(),
        ModelDb.Card<ElKidStrike>(),
        ModelDb.Card<ElKidStrike>(),
        ModelDb.Card<ElKidStrike>(),
        ModelDb.Card<ElKidDefend>(),
        ModelDb.Card<ElKidDefend>(),
        ModelDb.Card<ElKidDefend>(),
        ModelDb.Card<ElKidDefend>(),
        ModelDb.Card<BlinkStep>(),
        ModelDb.Card<WindUp>()
    ];

    public override IReadOnlyList<RelicModel> StartingRelics =>
    [
        ModelDb.Relic<PocketWatch>()
    ];
    
    public override CardPoolModel CardPool => ModelDb.CardPool<ElKidCardPool>();
    public override RelicPoolModel RelicPool => ModelDb.RelicPool<ElKidRelicPool>();
    public override PotionPoolModel PotionPool => ModelDb.PotionPool<ElKidPotionPool>();
    
    /*  PlaceholderCharacterModel will utilize placeholder basegame assets for most of your character assets until you
        override all the other methods that define those assets. 
        These are just some of the simplest assets, given some placeholders to differentiate your character with. 
        You don't have to, but you're suggested to rename these images. */
    public override Control CustomIcon
    {
        get
        {
            var icon = NodeFactory<Control>.CreateFromResource(CustomIconTexturePath);
            icon.SetAnchorsAndOffsetsPreset(Control.LayoutPreset.FullRect);
            return icon;
        }
    }
    // Layered Sprite2D rig + AnimationPlayer (idle/attack/cast/hurt/die), generated by tools/gen_character.py.
    // BaseLib converts the plain Node2D scene into NCreatureVisuals and routes animation triggers to the player.
    public override string CustomVisualPath => $"{MainFile.ResPath}/scenes/el_kid.tscn";

    public override string CustomIconTexturePath =>"character_icon_char_name.png".CharacterUiPath();
    public override string CustomCharacterSelectIconPath => "char_select_char_name.png".CharacterUiPath();
    public override string CustomCharacterSelectLockedIconPath => "char_select_char_name_locked.png".CharacterUiPath();
    public override string CustomMapMarkerPath => "map_marker_char_name.png".CharacterUiPath();
}